# Constants for Global Max

# Polynomial Constants
POLYNOMIAL_DEFAULT_MAX_DIMENSIONS = 4
POLYNOMIAL_DEFAULT_MAX_TERMS = 5

# Term Constants
TERM_DEFAULT_MAX_POWER = 5
TERM_DEFAULT_MIN_POWER = 0
TERM_DEFAULT_MIN_K = -1
TERM_DEFAULT_MAX_K = 1

# Gui Constants
GUI_DEFAULT_PLOT_RESOLUTION = 30
GUI_DEFAULT_FRAMES = 200
GUI_DEFAULT_MAX_POINTS = 1000

# Genetic algorithm
DEFAULT_POPULATION_SIZE = 500
